version: '3.9'

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network

services:
  es01:
    build: ./elasticsearch
    container_name: ${COMPOSE_PROJECT_NAME}_es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped

  es02:
    build: ./elasticsearch
    container_name: ${COMPOSE_PROJECT_NAME}_es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data02:/usr/share/elasticsearch/data
    restart: unless-stopped

  es03:
    build: ./elasticsearch
    container_name: ${COMPOSE_PROJECT_NAME}_es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data03:/usr/share/elasticsearch/data
    restart: unless-stopped
