version: '3.9'

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network

services:
  downloader:
    build: ./dump-processor/dump-downloader
    container_name: ${COMPOSE_PROJECT_NAME}_dump_downloader
    command: /bin/sh /usr/local/downloader.sh
    volumes:
      - ./dump-processor/dumps:/dumps
