version: '3.9'

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.0
    container_name: ${COMPOSE_PROJECT_NAME}_logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_SCHEME=${ELASTIC_SCHEME}
      - ELASTIC_PORT=${ELASTIC_PORT}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASS=${ELASTIC_PASS}
      - INDEX_SYSTEMS_WITH_COORDINATES=${INDEX_SYSTEMS_WITH_COORDINATES}
      - INDEX_SYSTEMS_WITHOUT_COORDINATES=${INDEX_SYSTEMS_WITHOUT_COORDINATES}
      - INDEX_CELESTIAL_BODIES=${INDEX_CELESTIAL_BODIES}
      - INDEX_POPULATED_SYSTEMS=${INDEX_POPULATED_SYSTEMS}
      - LOGSTASH_PORT_SYSTEMS_WITH_COORDINATES=${LOGSTASH_PORT_SYSTEMS_WITH_COORDINATES}
      - LOGSTASH_PORT_SYSTEMS_WITHOUT_COORDINATES=${LOGSTASH_PORT_SYSTEMS_WITHOUT_COORDINATES}
      - LOGSTASH_PORT_CELESTIAL_BODIES=${LOGSTASH_PORT_CELESTIAL_BODIES}
      - LOGSTASH_PORT_POPULATED_SYSTEMS=${LOGSTASH_PORT_POPULATED_SYSTEMS}
    volumes:
      - ./new-dump-processor/logstash/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./new-dump-processor/dumps:/dumps
    ports:
      - "5044:5044"
      - "5045:5045"
      - "5046:5046"
      - "5047:5047"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.0
    container_name: ${COMPOSE_PROJECT_NAME}_filebeat
    command: filebeat -e -strict.perms=false
    environment:
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT_SYSTEMS_WITH_COORDINATES=${LOGSTASH_PORT_SYSTEMS_WITH_COORDINATES}
      - LOGSTASH_PORT_SYSTEMS_WITHOUT_COORDINATES=${LOGSTASH_PORT_SYSTEMS_WITHOUT_COORDINATES}
      - LOGSTASH_PORT_CELESTIAL_BODIES=${LOGSTASH_PORT_CELESTIAL_BODIES}
      - LOGSTASH_PORT_POPULATED_SYSTEMS=${LOGSTASH_PORT_POPULATED_SYSTEMS}
    volumes:
      - ./new-dump-processor/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./new-dump-processor/dumps:/dumps
