networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network

services:
  backend:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    volumes:
      # - ./nextjs:/app/nextjs
      - ./seca.db:/app/seca.db
      - ./gamelogs:/app/gamelogs
    ports:
      - "8080:8080"
      - "3000:3000"
